### ISSUE TITLE
zh

### ISSUE THREAD

**Issue by ghost** [SavokBS/BrawlStars-v36#4]
поч best v36 brawl stars server, любая дудка со знанием реверсинга 36 либы сделает такой же (или даже лучше) сервер на 36

**Comment by OldAccount24678** [comment]
😟

**Comment by SavokBS** [comment]
потому что других серверов на 36 помимо каллисков нет на гитхабе, а у меня лучше  чем у них, поэтому best, вот сделай лучше и уберу

**Comment by OldAccount24678** [comment]
аааа

**Comment by ghost** [comment]
> потому что других серверов на 36 помимо каллисков нет на гитхабе, а у меня лучше чем у них, поэтому best, вот сделай лучше и уберу

ну тогда добавь open source
